version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
    versioning-strategy: "increase-if-necessary"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
        paths:
          - "test-requirements.txt"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
      - "tests"
    versioning-strategy: "increase-if-necessary"
    commit-message:
      prefix: "test"
      include: "scope"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
        dependency-name: "*"
        sourcefile: "test-requirements.txt"
